// ============================================
// BIST & NASDAQ Stock Lists + Dynamic Search
// ============================================

export interface StockItem {
    symbol: string;
    name: string;
    market: 'BIST' | 'NASDAQ';
}

// ====== BIST 100+ Popular Stocks ======
export const BIST_POPULAR: StockItem[] = [
    { symbol: 'THYAO', name: 'Türk Hava Yolları', market: 'BIST' },
    { symbol: 'GARAN', name: 'Garanti BBVA', market: 'BIST' },
    { symbol: 'ASELS', name: 'Aselsan', market: 'BIST' },
    { symbol: 'EREGL', name: 'Ereğli Demir Çelik', market: 'BIST' },
    { symbol: 'SISE', name: 'Şişecam', market: 'BIST' },
    { symbol: 'KCHOL', name: 'Koç Holding', market: 'BIST' },
    { symbol: 'SAHOL', name: 'Sabancı Holding', market: 'BIST' },
    { symbol: 'AKBNK', name: 'Akbank', market: 'BIST' },
    { symbol: 'YKBNK', name: 'Yapı Kredi Bankası', market: 'BIST' },
    { symbol: 'ISCTR', name: 'İş Bankası C', market: 'BIST' },
    { symbol: 'HALKB', name: 'Halkbank', market: 'BIST' },
    { symbol: 'VAKBN', name: 'Vakıfbank', market: 'BIST' },
    { symbol: 'TUPRS', name: 'Tüpraş', market: 'BIST' },
    { symbol: 'PETKM', name: 'Petkim', market: 'BIST' },
    { symbol: 'BIMAS', name: 'BİM Mağazaları', market: 'BIST' },
    { symbol: 'MGROS', name: 'Migros', market: 'BIST' },
    { symbol: 'TCELL', name: 'Turkcell', market: 'BIST' },
    { symbol: 'TTKOM', name: 'Türk Telekom', market: 'BIST' },
    { symbol: 'EKGYO', name: 'Emlak Konut GYO', market: 'BIST' },
    { symbol: 'ENKAI', name: 'Enka İnşaat', market: 'BIST' },
    { symbol: 'TOASO', name: 'Tofaş', market: 'BIST' },
    { symbol: 'FROTO', name: 'Ford Otosan', market: 'BIST' },
    { symbol: 'ARCLK', name: 'Arçelik', market: 'BIST' },
    { symbol: 'VESTL', name: 'Vestel', market: 'BIST' },
    { symbol: 'TAVHL', name: 'TAV Havalimanları', market: 'BIST' },
    { symbol: 'PGSUS', name: 'Pegasus', market: 'BIST' },
    { symbol: 'SASA', name: 'SASA Polyester', market: 'BIST' },
    { symbol: 'KOZAL', name: 'Koza Altın', market: 'BIST' },
    { symbol: 'KOZAA', name: 'Koza Anadolu Metal', market: 'BIST' },
    { symbol: 'DOHOL', name: 'Doğan Holding', market: 'BIST' },
    { symbol: 'GUBRF', name: 'Gübre Fabrikaları', market: 'BIST' },
    { symbol: 'SOKM', name: 'Şok Marketler', market: 'BIST' },
    { symbol: 'AEFES', name: 'Anadolu Efes', market: 'BIST' },
    { symbol: 'ULKER', name: 'Ülker', market: 'BIST' },
    { symbol: 'TTRAK', name: 'Türk Traktör', market: 'BIST' },
    { symbol: 'OTKAR', name: 'Otokar', market: 'BIST' },
    { symbol: 'DOAS', name: 'Doğuş Otomotiv', market: 'BIST' },
    { symbol: 'BRYAT', name: 'Borusan Yatırım', market: 'BIST' },
    { symbol: 'KRDMD', name: 'Kardemir D', market: 'BIST' },
    { symbol: 'ISGYO', name: 'İş GYO', market: 'BIST' },
    // Additional BIST Stocks (40+)
    { symbol: 'SNGYO', name: 'Sinpaş GYO', market: 'BIST' },
    { symbol: 'ALARK', name: 'Alarko Holding', market: 'BIST' },
    { symbol: 'AKSA', name: 'Aksa Akrilik', market: 'BIST' },
    { symbol: 'AYGAZ', name: 'Aygaz', market: 'BIST' },
    { symbol: 'BAGFS', name: 'Bagfaş', market: 'BIST' },
    { symbol: 'BANVT', name: 'Banvit', market: 'BIST' },
    { symbol: 'BRISA', name: 'Brisa', market: 'BIST' },
    { symbol: 'CCOLA', name: 'Coca-Cola İçecek', market: 'BIST' },
    { symbol: 'CEMAS', name: 'Çemaş Döküm', market: 'BIST' },
    { symbol: 'CIMSA', name: 'Çimsa', market: 'BIST' },
    { symbol: 'DEVA', name: 'Deva Holding', market: 'BIST' },
    { symbol: 'ECILC', name: 'Eczacıbaşı İlaç', market: 'BIST' },
    { symbol: 'ENJSA', name: 'Enerjisa Enerji', market: 'BIST' },
    { symbol: 'ESEN', name: 'Esenboğa Elektrik', market: 'BIST' },
    { symbol: 'GENIL', name: 'Gen İlaç', market: 'BIST' },
    { symbol: 'HEKTS', name: 'Hektaş', market: 'BIST' },
    { symbol: 'IPEKE', name: 'İpek Enerji', market: 'BIST' },
    { symbol: 'KARSN', name: 'Karsan Otomotiv', market: 'BIST' },
    { symbol: 'KONTR', name: 'Kontrolmatik', market: 'BIST' },
    { symbol: 'LOGO', name: 'Logo Yazılım', market: 'BIST' },
    { symbol: 'MAVI', name: 'Mavi Giyim', market: 'BIST' },
    { symbol: 'NETAS', name: 'Netaş Telekom', market: 'BIST' },
    { symbol: 'OYAKC', name: 'Oyak Çimento', market: 'BIST' },
    { symbol: 'PAPIL', name: 'Papilon Savunma', market: 'BIST' },
    { symbol: 'PENTA', name: 'Penta Teknoloji', market: 'BIST' },
    { symbol: 'QUAGR', name: 'QUA Granite', market: 'BIST' },
    { symbol: 'SMRTG', name: 'Smartiks Yazılım', market: 'BIST' },
    { symbol: 'TABGD', name: 'Tablo Gıda', market: 'BIST' },
    { symbol: 'TKFEN', name: 'Tekfen Holding', market: 'BIST' },
    { symbol: 'TMSN', name: 'Tümosan', market: 'BIST' },
    { symbol: 'TURSG', name: 'Türk Sigorta', market: 'BIST' },
    { symbol: 'VERUS', name: 'Verusaturk', market: 'BIST' },
    { symbol: 'YATAS', name: 'Yataş', market: 'BIST' },
    { symbol: 'ZOREN', name: 'Zorlu Enerji', market: 'BIST' },
    { symbol: 'AGHOL', name: 'AG Anadolu Grubu Holding', market: 'BIST' },
    { symbol: 'AKSEN', name: 'Aksa Enerji', market: 'BIST' },
    { symbol: 'ALFAS', name: 'Alfa Solar', market: 'BIST' },
    { symbol: 'ANSGR', name: 'Anadolu Sigorta', market: 'BIST' },
    { symbol: 'ASTOR', name: 'Astor Enerji', market: 'BIST' },
    { symbol: 'BERA', name: 'Bera Holding', market: 'BIST' },
    { symbol: 'BRLSM', name: 'Birleşim Mühendislik', market: 'BIST' },
    { symbol: 'BTCIM', name: 'Batıçim', market: 'BIST' },
    { symbol: 'BUCIM', name: 'Bursa Çimento', market: 'BIST' },
    { symbol: 'CANTE', name: 'Çan2 Termik', market: 'BIST' },
    { symbol: 'CLEBI', name: 'Çelebi Havacılık', market: 'BIST' },
    { symbol: 'CONSE', name: 'Consept Yazılım', market: 'BIST' },
    { symbol: 'CWENE', name: 'CW Enerji', market: 'BIST' },
    { symbol: 'DESA', name: 'Desa Deri', market: 'BIST' },
    { symbol: 'EGEEN', name: 'Ege Endüstri', market: 'BIST' },
    { symbol: 'EUPWR', name: 'Europower Enerji', market: 'BIST' },
    { symbol: 'GESAN', name: 'Giresun Ticaret', market: 'BIST' },
    { symbol: 'GLYHO', name: 'Global Yatırım Holding', market: 'BIST' },
    { symbol: 'GSDHO', name: 'GSD Holding', market: 'BIST' },
    { symbol: 'HDFGS', name: 'Hedef Girişim', market: 'BIST' },
    { symbol: 'HUNER', name: 'Hünkar Orman', market: 'BIST' },
    { symbol: 'INDES', name: 'İndeks Bilgisayar', market: 'BIST' },
    { symbol: 'ISMEN', name: 'İş Yatırım', market: 'BIST' },
    { symbol: 'KARTN', name: 'Kartonsan', market: 'BIST' },
    { symbol: 'KAYSE', name: 'Kayseri Şeker', market: 'BIST' },
    { symbol: 'KLNMA', name: 'Türkiye Kalkınma', market: 'BIST' },
    { symbol: 'KONKA', name: 'Konya Kağıt', market: 'BIST' },
    { symbol: 'KORDS', name: 'Kordsa', market: 'BIST' },
    { symbol: 'LKMNH', name: 'Lokman Hekim', market: 'BIST' },
    { symbol: 'MAGEN', name: 'Margün Enerji', market: 'BIST' },
    { symbol: 'MERCN', name: 'Mercan Kimya', market: 'BIST' },
    { symbol: 'MIATK', name: 'Mia Teknoloji', market: 'BIST' },
    { symbol: 'MPARK', name: 'MLP Sağlık', market: 'BIST' },
    { symbol: 'NUHCM', name: 'Nuh Çimento', market: 'BIST' },
    { symbol: 'OSMEN', name: 'Osmanlı Yatırım', market: 'BIST' },
    { symbol: 'PARSN', name: 'Parsan', market: 'BIST' },
    { symbol: 'PCILT', name: 'PC İletişim', market: 'BIST' },
    { symbol: 'POLHO', name: 'Polisan Holding', market: 'BIST' },
    { symbol: 'REEDR', name: 'Reedr Teknoloji', market: 'BIST' },
    { symbol: 'RGYAS', name: 'Reysaş GYO', market: 'BIST' },
    { symbol: 'RYSAS', name: 'Reysaş Taşımacılık', market: 'BIST' },
    { symbol: 'SELEC', name: 'Selçuk Ecza', market: 'BIST' },
    { symbol: 'SKBNK', name: 'Şekerbank', market: 'BIST' },
    { symbol: 'SUNTK', name: 'Suntekstil', market: 'BIST' },
    { symbol: 'TATGD', name: 'Tat Gıda', market: 'BIST' },
    { symbol: 'TBORG', name: 'T. Tuborg', market: 'BIST' },
    { symbol: 'TICNO', name: 'Ticaret A.Ş.', market: 'BIST' },
    { symbol: 'TRILC', name: 'Turk İlaç Serum', market: 'BIST' },
    { symbol: 'TSGYO', name: 'TSKB GYO', market: 'BIST' },
    { symbol: 'TSKB', name: 'TSKB', market: 'BIST' },
    { symbol: 'TUREX', name: 'Tureks Turizm', market: 'BIST' },
    { symbol: 'ULUUN', name: 'Ulusoy Un', market: 'BIST' },
    { symbol: 'UNLU', name: 'Ünlü & Co', market: 'BIST' },
    { symbol: 'USAK', name: 'Uşak Seramik', market: 'BIST' },
    { symbol: 'VAKFN', name: 'Vakıf Finansal', market: 'BIST' },
    { symbol: 'YKSLN', name: 'Yüksel İnşaat', market: 'BIST' },
];

// ====== NASDAQ/US 100+ Popular Stocks ======
export const NASDAQ_POPULAR: StockItem[] = [
    { symbol: 'AAPL', name: 'Apple', market: 'NASDAQ' },
    { symbol: 'MSFT', name: 'Microsoft', market: 'NASDAQ' },
    { symbol: 'GOOGL', name: 'Alphabet (Google)', market: 'NASDAQ' },
    { symbol: 'AMZN', name: 'Amazon', market: 'NASDAQ' },
    { symbol: 'NVDA', name: 'NVIDIA', market: 'NASDAQ' },
    { symbol: 'META', name: 'Meta (Facebook)', market: 'NASDAQ' },
    { symbol: 'TSLA', name: 'Tesla', market: 'NASDAQ' },
    { symbol: 'NFLX', name: 'Netflix', market: 'NASDAQ' },
    { symbol: 'AMD', name: 'AMD', market: 'NASDAQ' },
    { symbol: 'INTC', name: 'Intel', market: 'NASDAQ' },
    { symbol: 'AVGO', name: 'Broadcom', market: 'NASDAQ' },
    { symbol: 'COST', name: 'Costco', market: 'NASDAQ' },
    { symbol: 'PEP', name: 'PepsiCo', market: 'NASDAQ' },
    { symbol: 'ADBE', name: 'Adobe', market: 'NASDAQ' },
    { symbol: 'CSCO', name: 'Cisco', market: 'NASDAQ' },
    { symbol: 'CRM', name: 'Salesforce', market: 'NASDAQ' },
    { symbol: 'QCOM', name: 'Qualcomm', market: 'NASDAQ' },
    { symbol: 'PYPL', name: 'PayPal', market: 'NASDAQ' },
    { symbol: 'UBER', name: 'Uber', market: 'NASDAQ' },
    { symbol: 'ABNB', name: 'Airbnb', market: 'NASDAQ' },
    { symbol: 'SQ', name: 'Block (Square)', market: 'NASDAQ' },
    { symbol: 'COIN', name: 'Coinbase', market: 'NASDAQ' },
    { symbol: 'SPOT', name: 'Spotify', market: 'NASDAQ' },
    { symbol: 'ZM', name: 'Zoom', market: 'NASDAQ' },
    { symbol: 'SHOP', name: 'Shopify', market: 'NASDAQ' },
    { symbol: 'SNAP', name: 'Snap', market: 'NASDAQ' },
    { symbol: 'RBLX', name: 'Roblox', market: 'NASDAQ' },
    { symbol: 'PLTR', name: 'Palantir', market: 'NASDAQ' },
    { symbol: 'PANW', name: 'Palo Alto Networks', market: 'NASDAQ' },
    { symbol: 'CRWD', name: 'CrowdStrike', market: 'NASDAQ' },
    { symbol: 'MELI', name: 'MercadoLibre', market: 'NASDAQ' },
    { symbol: 'LULU', name: 'Lululemon', market: 'NASDAQ' },
    { symbol: 'DDOG', name: 'Datadog', market: 'NASDAQ' },
    { symbol: 'NET', name: 'Cloudflare', market: 'NASDAQ' },
    { symbol: 'SNOW', name: 'Snowflake', market: 'NASDAQ' },
    { symbol: 'ARM', name: 'ARM Holdings', market: 'NASDAQ' },
    { symbol: 'SMCI', name: 'Super Micro Computer', market: 'NASDAQ' },
    { symbol: 'MRVL', name: 'Marvell Technology', market: 'NASDAQ' },
    { symbol: 'MU', name: 'Micron', market: 'NASDAQ' },
    // Additional NASDAQ/US Stocks (60+)
    { symbol: 'DIS', name: 'Walt Disney', market: 'NASDAQ' },
    { symbol: 'BA', name: 'Boeing', market: 'NASDAQ' },
    { symbol: 'V', name: 'Visa', market: 'NASDAQ' },
    { symbol: 'MA', name: 'Mastercard', market: 'NASDAQ' },
    { symbol: 'JPM', name: 'JPMorgan Chase', market: 'NASDAQ' },
    { symbol: 'GS', name: 'Goldman Sachs', market: 'NASDAQ' },
    { symbol: 'MS', name: 'Morgan Stanley', market: 'NASDAQ' },
    { symbol: 'BAC', name: 'Bank of America', market: 'NASDAQ' },
    { symbol: 'WFC', name: 'Wells Fargo', market: 'NASDAQ' },
    { symbol: 'C', name: 'Citigroup', market: 'NASDAQ' },
    { symbol: 'JNJ', name: 'Johnson & Johnson', market: 'NASDAQ' },
    { symbol: 'PFE', name: 'Pfizer', market: 'NASDAQ' },
    { symbol: 'MRNA', name: 'Moderna', market: 'NASDAQ' },
    { symbol: 'LLY', name: 'Eli Lilly', market: 'NASDAQ' },
    { symbol: 'UNH', name: 'UnitedHealth', market: 'NASDAQ' },
    { symbol: 'ABBV', name: 'AbbVie', market: 'NASDAQ' },
    { symbol: 'NKE', name: 'Nike', market: 'NASDAQ' },
    { symbol: 'KO', name: 'Coca-Cola', market: 'NASDAQ' },
    { symbol: 'MCD', name: "McDonald's", market: 'NASDAQ' },
    { symbol: 'SBUX', name: 'Starbucks', market: 'NASDAQ' },
    { symbol: 'WMT', name: 'Walmart', market: 'NASDAQ' },
    { symbol: 'HD', name: 'Home Depot', market: 'NASDAQ' },
    { symbol: 'TGT', name: 'Target', market: 'NASDAQ' },
    { symbol: 'XOM', name: 'Exxon Mobil', market: 'NASDAQ' },
    { symbol: 'CVX', name: 'Chevron', market: 'NASDAQ' },
    { symbol: 'COP', name: 'ConocoPhillips', market: 'NASDAQ' },
    { symbol: 'GE', name: 'General Electric', market: 'NASDAQ' },
    { symbol: 'CAT', name: 'Caterpillar', market: 'NASDAQ' },
    { symbol: 'DE', name: 'Deere & Company', market: 'NASDAQ' },
    { symbol: 'F', name: 'Ford Motor', market: 'NASDAQ' },
    { symbol: 'GM', name: 'General Motors', market: 'NASDAQ' },
    { symbol: 'TM', name: 'Toyota', market: 'NASDAQ' },
    { symbol: 'RIVN', name: 'Rivian', market: 'NASDAQ' },
    { symbol: 'LCID', name: 'Lucid Motors', market: 'NASDAQ' },
    { symbol: 'NIO', name: 'NIO', market: 'NASDAQ' },
    { symbol: 'BABA', name: 'Alibaba', market: 'NASDAQ' },
    { symbol: 'JD', name: 'JD.com', market: 'NASDAQ' },
    { symbol: 'PDD', name: 'PDD Holdings (Temu)', market: 'NASDAQ' },
    { symbol: 'TSM', name: 'TSMC', market: 'NASDAQ' },
    { symbol: 'ASML', name: 'ASML', market: 'NASDAQ' },
    { symbol: 'DELL', name: 'Dell Technologies', market: 'NASDAQ' },
    { symbol: 'HPQ', name: 'HP', market: 'NASDAQ' },
    { symbol: 'IBM', name: 'IBM', market: 'NASDAQ' },
    { symbol: 'ORCL', name: 'Oracle', market: 'NASDAQ' },
    { symbol: 'NOW', name: 'ServiceNow', market: 'NASDAQ' },
    { symbol: 'WDAY', name: 'Workday', market: 'NASDAQ' },
    { symbol: 'ZS', name: 'Zscaler', market: 'NASDAQ' },
    { symbol: 'OKTA', name: 'Okta', market: 'NASDAQ' },
    { symbol: 'MDB', name: 'MongoDB', market: 'NASDAQ' },
    { symbol: 'TEAM', name: 'Atlassian', market: 'NASDAQ' },
    { symbol: 'TWLO', name: 'Twilio', market: 'NASDAQ' },
    { symbol: 'U', name: 'Unity Software', market: 'NASDAQ' },
    { symbol: 'ROKU', name: 'Roku', market: 'NASDAQ' },
    { symbol: 'PINS', name: 'Pinterest', market: 'NASDAQ' },
    { symbol: 'LYFT', name: 'Lyft', market: 'NASDAQ' },
    { symbol: 'DASH', name: 'DoorDash', market: 'NASDAQ' },
    { symbol: 'GRAB', name: 'Grab Holdings', market: 'NASDAQ' },
    { symbol: 'SE', name: 'Sea Limited', market: 'NASDAQ' },
    { symbol: 'SQ', name: 'Block', market: 'NASDAQ' },
    { symbol: 'SOFI', name: 'SoFi Technologies', market: 'NASDAQ' },
    { symbol: 'HOOD', name: 'Robinhood', market: 'NASDAQ' },
    { symbol: 'AFRM', name: 'Affirm', market: 'NASDAQ' },
    { symbol: 'UPST', name: 'Upstart', market: 'NASDAQ' },
    { symbol: 'BILL', name: 'Bill.com', market: 'NASDAQ' },
    { symbol: 'HUBS', name: 'HubSpot', market: 'NASDAQ' },
    { symbol: 'TTD', name: 'The Trade Desk', market: 'NASDAQ' },
    { symbol: 'MTCH', name: 'Match Group', market: 'NASDAQ' },
    { symbol: 'ETSY', name: 'Etsy', market: 'NASDAQ' },
    { symbol: 'W', name: 'Wayfair', market: 'NASDAQ' },
    { symbol: 'CHWY', name: 'Chewy', market: 'NASDAQ' },
    { symbol: 'DUOL', name: 'Duolingo', market: 'NASDAQ' },
    { symbol: 'RKLB', name: 'Rocket Lab', market: 'NASDAQ' },
    { symbol: 'IONQ', name: 'IonQ', market: 'NASDAQ' },
    { symbol: 'AI', name: 'C3.ai', market: 'NASDAQ' },
    { symbol: 'PATH', name: 'UiPath', market: 'NASDAQ' },
    { symbol: 'GTLB', name: 'GitLab', market: 'NASDAQ' },
    { symbol: 'CFLT', name: 'Confluent', market: 'NASDAQ' },
    { symbol: 'DOCN', name: 'DigitalOcean', market: 'NASDAQ' },
    { symbol: 'CELH', name: 'Celsius Holdings', market: 'NASDAQ' },
];

// Local search (popular stocks only — for instant results, 100+ each)
export function searchStocksLocal(query: string, market?: 'BIST' | 'NASDAQ'): StockItem[] {
    const q = query.toLowerCase();
    const stocks = market === 'BIST' ? BIST_POPULAR
        : market === 'NASDAQ' ? NASDAQ_POPULAR
            : [...BIST_POPULAR, ...NASDAQ_POPULAR];
    if (!q) return stocks;
    return stocks.filter(
        (s) => s.symbol.toLowerCase().includes(q) || s.name.toLowerCase().includes(q)
    );
}

// Dynamic search via API (searches ALL stocks globally)
export async function searchStocksAPI(query: string, market: 'BIST' | 'NASDAQ'): Promise<StockItem[]> {
    if (!query || query.length < 1) return [];
    try {
        // For BIST searches, append .IS hint for better results
        const searchQuery = market === 'BIST' ? `${query}.IS` : query;
        const res = await fetch(`/api/search-stocks?q=${encodeURIComponent(searchQuery)}&market=${market}`);
        if (!res.ok) return [];
        const data = await res.json();
        return data.results || [];
    } catch {
        return [];
    }
}
